<?php

namespace App\Services\Network;

/**
 * Domain-generation and resolution-failure rules for this host's own DNS.
 *
 * Reads the events `DnsEventNormalizer` produces, so everything here is this
 * host asking a resolver a question (measured there: src_ip was this host on
 * 21,088 of 21,092 rows, dest_port 53 on all of them). Nothing in this file
 * describes queries we received, because none reach the logger.
 *
 * **The corpus.** Thresholds below were measured on 23,338 `event_type: dns`
 * rows taken from /var/log/suricata/eve.json on 28 August, spanning
 * 23:05:29 to 23:54:04 (2,914 seconds): 11,696 queries, 11,642 answers, 42
 * distinct rrnames, 255 NXDOMAIN answers (2.19% of answers) over 4 distinct
 * NXDOMAIN names. The corpus limit `DnsEventNormalizer` records still holds:
 * the seven rotated generations contain 0 dns rows, so this is the whole DNS
 * history that exists on this host, and every "max observed" below is a
 * maximum over 49 minutes rather than over a week. Where a number in the module
 * brief disagreed with the file, the file won, and the disagreement is recorded
 * next to the threshold it affects.
 *
 * **Entropy alone cannot work here, and the measurement is worse than the
 * brief says.** Three separate results, all from the corpus above:
 *
 * 1. The highest leftmost-label entropy in this host's entire DNS history is
 *    3.88, and it is ours: `no-such-host-abc123xyz.invalid`, 8 NXDOMAIN
 *    lookups, generated by this project's own test suite
 *    (tests/Unit/NetworkContainmentTest.php asks the containment code to
 *    resolve it). The next highest are 3.096 (`nginx-proxy`, a Docker service
 *    name) and 3.039 (`saasaccounting.intellitrustme.com`). So a
 *    single-name entropy rule set anywhere below 3.88 fires on the product's own
 *    unit tests, and set above it fires on nothing at all.
 * 2. Shannon entropy over a label is bounded by log2(length), so it is not
 *    scale free: on a 12-character label the ceiling is 3.585, and this host's
 *    legitimate labels already sit at 87 to 90% of their own ceiling
 *    (`nginx-proxy`, 11 characters, 3.096 against a ceiling of 3.459).
 * 3. Measured on five seeded sets of 30 random 12-character base36 labels, the
 *    kind of label a DGA emits: entropy ranges 2.689 to 3.585 with a median of
 *    3.25. A threshold high enough to clear this host's legitimate traffic
 *    (>3.10) therefore sits INSIDE the DGA distribution and drops roughly half
 *    of a real burst, one name at a time.
 *
 * So entropy is used in exactly one place: as corroboration averaged over the
 * whole set of names in a burst, where it is stable (mean 3.284 to 3.317 across
 * those five synthetic sets, against a maximum of 2.888 for any real parent
 * group on this host). It never triggers anything on its own.
 *
 * **What does discriminate: distinct count, not rate.** The measured NXDOMAIN
 * names are a small repeated set, exactly as the brief said. Over sliding
 * windows of 60, 120, 300, 600 and 900 seconds, the maximum number of DISTINCT
 * NXDOMAIN names seen under any one parent domain was 1, at every window size.
 * Host wide it was 3 (windows up to 600s) and 4 (900s). The same traffic sends
 * 255 NXDOMAIN answers, so rate and count say completely different things here:
 * `host.docker.internal` was refused 181 times and is one name.
 *
 * **The other measurement that sets the window.** In a 60-second window this
 * host's NXDOMAIN share reaches 34.6% of 104 answers, which would be an alert
 * on any rate rule; at 300 seconds the same traffic peaks at 12.5% (denominator
 * >= 20) and 8.0% (denominator >= 50). A rate rule is therefore only honest
 * over a window long enough to have a denominator, and it is graded low here
 * for the same reason.
 *
 * **Ordering, and why there is no `learn()`.** `NetworkRuleEngine` learns after
 * the whole batch is judged, so that one event cannot teach the baseline that
 * the next event is normal. The opposite is required here: `evaluate()` folds
 * the event into the window BEFORE judging it, because the window is evidence
 * rather than normality, and a burst that arrives inside one batch would
 * otherwise be invisible (the same reason `SpoolIdentityHistory` counts the
 * current batch). Re-evaluating an event twice cannot inflate a finding, since
 * DNS-001 and DNS-002 count distinct names and DNS-003 divides two counters
 * that would both double.
 *
 * **The clock is the event's, not `time()`.** The window is pruned against the
 * highest event time seen so far, so a replay of yesterday's log judges with
 * yesterday's clock instead of finding every window empty. Measured, the log is
 * very nearly ordered: 265 of 23,338 rows arrive out of order, by at most
 * 2.841ms, which cannot move an event across a 300-second boundary.
 *
 * **Why this file dedupes at all.** `EdrRuleGovernor::signatureFor()` builds its
 * suppression key from rule, username, binary name and command line. A DNS
 * event has none of those (measured in `DnsEventNormalizer`: no process
 * attribution exists in this data, pid 0 and empty path on 100% of rows), so
 * every DNS finding of one rule collapses to the same governor signature no
 * matter which domain it is about. Two consequences, both handled here rather
 * than upstream: a 30-name burst must produce one finding and not nineteen, and
 * a low or medium severity DNS rule that fires five times during the learning
 * window would be suppressed by `matches_baseline` for every domain
 * simultaneously. That is why the low-severity rule below is the one with a
 * denominator floor and a cooldown, and why the two counting rules are graded
 * high (`ALWAYS_ALERT_SEVERITIES` exempts high and critical from that
 * suppression).
 *
 * **The window state, and which store was chosen.** Three existing candidates
 * were considered and none of them can hold this evidence.
 *
 * `DomainResolutionMap` is the closest fit by name and the furthest by content:
 * it indexes a domain against the addresses it resolved to, and `record()`
 * skips an answer that names no address outright (its own `no_addresses`
 * counter). Every answer these rules count is NXDOMAIN, which by definition
 * carries no address, so that store would be handed the whole burst and keep
 * none of it. It also holds mappings for a TTL plus a grace, up to six hours,
 * against whole-second timestamps, which is a different retention question from
 * a 300-second window.
 *
 * `NetworkBaselineStore` is keyed on (process_path, remote_address,
 * service_port) and counts distinct calendar days, whereas DNS has no process
 * at all (pid 0 and an empty path on every row, by design) and the question
 * here is sub-hour: every DNS row would collapse into one row keyed on the
 * empty path.
 *
 * The event spool cannot be the window either. It is already row-capped at
 * 500,000 with retention collapsed to 1.42 hours (`NetworkCollector`), and this
 * host produces DNS at 23,338 rows per 49 minutes, roughly 690,000 a day on its
 * own.
 *
 * So the window is a small dedicated structure, `DnsResolutionWindow`, taken as
 * a constructor dependency: one entry per distinct NXDOMAIN name in the window
 * plus ten 30-second counter buckets, in memory, with no database of its own.
 * Measured worst case on this host: 34 distinct names and 1,810 answers in a
 * 600-second window, so a few kilobytes.
 *
 * It started life as a second class inside this file, since these rules are its
 * only reader, and that was wrong for a reason worth recording: PSR-4 maps one
 * class per file, so `new DnsResolutionWindow()` in a caller that had not
 * already loaded this file was a fatal error, and whether it loaded first
 * depended on the order of two expressions on one line. It has its own file.
 * `DnsAnomalyRules` still constructs one by default, and `window()` exposes the
 * instance for a caller that needs to persist or share it.
 *
 * **The state must be persisted by the caller, and this is not optional.**
 * Measured on this host, the EDR cycle is `ids:sync-edr` run by
 * security-one-watchdog.sh in a fresh PHP process every 30 seconds
 * (EDR_INTERVAL=30). A window held only in memory therefore holds 30 seconds,
 * not 300, and a burst spread thinner than 12 names per cycle would never fire.
 * `DnsResolutionWindow::export()` and `restore()` exist for that, and
 * `basis()` reports the span actually observed so the gap is visible rather
 * than silent.
 *
 * **Absence of history is not evidence of intrusion, and a null result is not a
 * clean bill of health.** Nothing here treats a first sighting as malice: a
 * name this host has never resolved before is not a finding, because there is
 * no domain history on this host to judge novelty against (the whole DNS corpus
 * is 49 minutes long). DNS-003 refuses to judge until it has 50 answers to
 * divide by, and counts the refusal in `withheld()` so "we had no basis" can be
 * reported separately from "the rate was normal".
 *
 * **The rule id space is shared.** DNS-001 to DNS-004 are the generation rules
 * in this file; `DnsTunnelRules` holds DNS-010 upward for the tunnelling
 * detections. Anything added here has to stay under DNS-010.
 *
 * @see DnsEventNormalizer for the event shape, and for why DNS cannot be
 *      aggregated by ConnectionAggregator or filtered by shouldDrop().
 * @see NetworkRuleEngine for the finding structure these rules follow.
 * @see DomainResolutionMap for the address attribution store, which answers a
 *      different question and cannot hold an answer that named no address.
 */
class DnsAnomalyRules
{
    /**
     * The window every counting rule is measured over.
     *
     * 300 seconds, for two measured reasons. Shorter windows make the rate
     * meaningless (at 60 seconds this host's own NXDOMAIN share peaks at 34.6%
     * of 104 answers, against 12.5% at 300 seconds), and longer ones buy
     * nothing for the distinct-count rules (the maximum distinct NXDOMAIN names
     * under one parent was 1 at 60, 120, 300, 600 and 900 seconds alike). It is
     * also ten of the measured 30-second collection cycles, so the caller has
     * to carry the window across cycles for it to mean what it says.
     */
    public const WINDOW_SECONDS = 300;

    /**
     * DNS-001: distinct non-existent names under one parent domain.
     *
     * Measured maximum on this host: 1, at every window size from 60 to 900
     * seconds, over 255 NXDOMAIN answers. The names are a repeated set
     * (host.docker.internal 181, nginx-proxy 64, no-such-host-abc123xyz.invalid
     * 8, invalid 2), which is why the distinct count and not the rate is the
     * trigger.
     *
     * 12 is a twelvefold margin on that maximum, and it is also large relative
     * to everything this host does: the maximum number of distinct names of any
     * rcode resolved in a 300-second window is 32 (34 at 600 seconds). So 12
     * distinct non-existent names under a single parent is more than a third of
     * this host's entire distinct-name volume for the window, which is not a
     * shape a search-domain suffix list or a broken client produces here.
     */
    private const NX_DISTINCT_PER_PARENT = 12;

    /**
     * DNS-002: distinct non-existent names host wide, spread across parents.
     *
     * The single-parent rule above cannot see a DGA that spreads across TLDs,
     * and it cannot see one that uses single-label names at all (each is its
     * own parent). Measured maximum host wide: 3 distinct NXDOMAIN names in any
     * window up to 600 seconds, 4 at 900 seconds, drawn from 4 distinct parents
     * across the whole corpus. 18 names is a 4.5x margin on the worst window
     * observed.
     *
     * The parent floor was supposed to keep this from restating DNS-001 for a
     * one-parent burst, and it did not. This host's everyday NXDOMAIN traffic
     * is two names under two parents — a Docker hostname and a container
     * service name, 96% of the corpus NXDOMAIN — so a burst under a single
     * parent arrives with two of the three required parents already in the
     * window. Every DNS-001 came with a DNS-002 beside it saying the same thing
     * less specifically, and a responder who sees two rules agree reads that as
     * two pieces of evidence when it is one.
     *
     * So the two conditions are made disjoint on the fact that separates them.
     * DNS-001 fires when one parent holds NX_DISTINCT_PER_PARENT names; DNS-002
     * requires that no parent does. They cannot both fire on the same window,
     * and DNS-002 now means what its name says: names spread across domains,
     * not concentrated under one.
     *
     * What it costs: a burst that is both — enough under one parent and enough
     * host wide — is reported by DNS-001 alone. That is the more specific of
     * the two, it names the parent, and it is the one a responder can act on.
     */
    private const NX_DISTINCT_HOST_WIDE = 18;
    private const NX_HOST_WIDE_MIN_PARENTS = 3;

    /**
     * DNS-003: the share of answers in the window that were NXDOMAIN.
     *
     * Baseline share 2.19% (255 of 11,642 answers). Maximum in a trailing
     * 300-second window: 12.5% with a denominator of at least 20, 8.0% with at
     * least 50, 6.9% with at least 100. 25% is a threefold margin on the 50
     * case, and a DGA burst of 30 names against this host's typical 300-second
     * answer volume lands well above it.
     *
     * The floor exists because the rate is meaningless without a denominator:
     * the minimum number of answers in a trailing 300-second window here is 1,
     * where a single refused Docker hostname reads as 100%. 50 is reached in
     * normal operation almost immediately (p10 of answers in a trailing
     * 300-second window is 689, median 1,247), so the floor costs no coverage
     * while removing the only shape that produced a spurious rate.
     */
    private const NX_RATE = 0.25;
    private const NX_RATE_MIN_ANSWERS = 50;

    /**
     * DNS-004: the conjunction that identifies one algorithmically built label.
     *
     * Measured over all 23,338 rows, each condition on its own and then
     * together:
     *   leftmost entropy >= 3.4        16 events, 1 distinct name (ours, the
     *                                  test-suite probe)
     *   leftmost label >= 12 chars    768 events, 5 distinct names
     *                                  (cybersecureone.com,
     *                                   waf-frankfurt.cybersecureone.com,
     *                                   saasaccounting.intellitrustme.com, ...)
     *   digit ratio >= 0.2              0 events, 0 names
     *   all three together              0 events, 0 names
     *
     * The digit ratio is doing the work, which matches the brief: the leftmost
     * label of a legitimate name on this host essentially never contains
     * digits. Maximum observed is 0.167
     * (`auth-4.8.5.security-status.secpoll.powerdns.com`, this host's own
     * PowerDNS version check) and then 0.125 (`clients2.google.com`); p99 over
     * distinct names is 0.167 and p99 over events is 0.0.
     *
     * Entropy is set at 3.0 rather than 3.4 here deliberately. It costs nothing
     * on real traffic, because the digit condition is the binding one and
     * hits 0 rows either way, and it recovers the DGA labels that happen to
     * repeat a character: measured on random 12-character base36 labels,
     * entropy runs 2.689 to 3.585 with a median of 3.25, so a 3.4 cut discards
     * about half of them.
     *
     * What this rule cannot see, stated because a gap that is not written down
     * gets rediscovered as an incident: a purely alphabetic DGA (Conficker's
     * shape) has a digit ratio of 0 and will not trip it. That case is DNS-001's
     * job, which does not care what alphabet the names use. And the known false
     * positive class elsewhere is CDN hash labels, `d1x2y3z4a5b6.cloudfront.net`
     * and Akamai edge names, which have digits, length and entropy for
     * legitimate reasons. None appear in this host's corpus; on a host that
     * fronts its assets with one, this rule needs a domain baseline before it is
     * worth more than the medium severity it carries.
     */
    private const DGA_MIN_ENTROPY = 3.0;
    private const DGA_MIN_DIGIT_RATIO = 0.2;
    private const DGA_MIN_LABEL_LENGTH = 12;

    /**
     * What raises a burst from high to critical.
     *
     * Corroboration only, never a trigger, and measured over sets of names
     * rather than single names because that is where entropy is stable.
     * Real parent groups on this host (those with more than one name):
     * mean leftmost entropy 1.761 to 2.888, maximum single label 3.039, and 0
     * of 21 names in any group carrying a digit ratio of 0.2 or more. Five
     * seeded synthetic bursts of 30 random 12-character labels: mean entropy
     * 3.284 to 3.317, with 18 to 25 names of 30 above the digit ratio.
     *
     * The mean threshold is 3.10, which is the highest entropy any single
     * legitimate label on this host reaches (`nginx-proxy`, 3.096). Requiring
     * the burst's MEAN to clear this host's individual maximum is the
     * conservative form of a measurement the brief warns is too thin to use
     * directly.
     */
    private const CORROBORATION_MEAN_ENTROPY = 3.10;
    private const CORROBORATION_DIGIT_SHARE = 0.5;

    /**
     * Public suffixes that are two labels long.
     *
     * Without these, "the parent domain" of a.b.com.tw would be com.tw and
     * every unrelated Taiwanese domain would share one group, which makes
     * DNS-001 more sensitive rather than less and could group unrelated
     * failures into a burst. Measured, 0 names in this corpus sit under any of
     * them, so this list fires on nothing today; it is here because the corpus
     * does contain .tw traffic (`sp.spx.shopee.tw`) and this product's
     * customers are Taiwanese, so com.tw is the realistic first arrival. This
     * is deliberately a short list and not a public suffix list: a full PSL is
     * a data dependency, and the failure mode of a missing entry is a coarser
     * group, which is visible in the finding's reason rather than silent.
     */
    private const MULTI_PART_SUFFIXES = [
        'com.tw', 'org.tw', 'net.tw', 'gov.tw', 'edu.tw',
        'co.uk', 'org.uk', 'gov.uk', 'ac.uk',
        'com.cn', 'com.hk', 'com.sg', 'com.au', 'net.au', 'com.br', 'com.mx',
        'co.jp', 'co.kr', 'co.in', 'co.za', 'com.tr',
    ];

    private DnsResolutionWindow $window;

    /** @var array<string, int> rule => times a judgement was withheld */
    private array $withheld = [];

    public function __construct(?DnsResolutionWindow $window = null)
    {
        $this->window = $window ?? new DnsResolutionWindow(self::WINDOW_SECONDS);
    }

    /**
     * The window these rules are counting over.
     *
     * Exposed so the caller can persist it across the measured 30-second
     * process boundary (see the class docblock) and so a second rules instance
     * can share one window rather than each holding a partial view.
     */
    public function window(): DnsResolutionWindow
    {
        return $this->window;
    }

    /**
     * @param array $event a normalised DNS event from DnsEventNormalizer
     * @return array<int, array> findings, in the shape NetworkRuleEngine uses
     */
    /** Names dropped whole as reverse lookups, so the exclusion is visible. */
    private int $excludedReverse = 0;

    /** Names judged on what was left after an address was stripped from the front. */
    private int $reducedReverse = 0;

    public function evaluate(array $event): array
    {
        $action = (string) ($event['action'] ?? '');

        if (!str_starts_with($action, 'dns_')) {
            return [];
        }

        $dns = is_array($event['dns'] ?? null) ? $event['dns'] : [];
        $name = (string) ($dns['rrname'] ?? '');

        if ($name === '') {
            return [];
        }

        // A query carries no rcode, so it cannot contribute to any of the
        // counters below. It is still worth keeping the early return explicit:
        // an earlier draft folded queries into the answer denominator, which
        // halved every rate on a host that logs both halves of the exchange.
        if ($action !== 'dns_answer') {
            return [];
        }

        // The address in front of a name is removed before anything below
        // counts it.
        //
        // Resolving an address queries a name of digit labels ending in
        // in-addr.arpa, and an address with no PTR record answers NXDOMAIN. A
        // blocklist lookup is the same shape with a zone on the end, and "not
        // listed" is also NXDOMAIN. So anything resolving or checking addresses
        // in bulk produces exactly what these rules key on: many distinct,
        // digit-heavy, non-existent names in a short window. DNS-001 graded
        // that critical. The corpus holds 10 such lookups
        // (138.77.249.66.in-addr.arpa and similar); a log analyser or a mail
        // server makes hundreds an hour.
        //
        // Stripping rather than skipping, because skipping was a hiding place:
        // four leading digit labels cost an attacker nothing and exempted the
        // whole name. Stripped, a blocklist lookup collapses to its zone —
        // one repeated name however many addresses are checked — while
        // 1.2.3.4.<payload>.example.net is judged on the payload.
        //
        // Counted rather than silently dropped: an exclusion nobody can see is
        // indistinguishable from a rule that does not work.
        $remainder = DnsEventNormalizer::reverseLookupRemainder($name);

        if ($remainder !== null) {
            if ($remainder === '') {
                $this->excludedReverse++;

                return [];
            }

            $this->reducedReverse++;
            $name = $remainder;
        }

        $rcode = $dns['rcode'] ?? null;
        $isNxdomain = $rcode === 'NXDOMAIN';
        $parent = $this->parentDomain($name);
        $ts = $this->eventTime($event);

        $this->window->observe($name, $parent, $isNxdomain, $ts);

        $findings = [];

        /* DNS-001 - many distinct non-existent names under one parent --------
         * The primary rule, and the trigger is the distinct count. Measured on
         * this host the same 300-second window never held more than 1 distinct
         * NXDOMAIN name under any parent, while it held 255 NXDOMAIN answers:
         * a rate rule reads that as constant failure, a distinct-count rule
         * reads it as one Docker hostname and one container service name being
         * asked for over and over. */
        if ($isNxdomain) {
            $names = $this->window->distinctNxdomainNames($parent);

            if (count($names) >= self::NX_DISTINCT_PER_PARENT
                && $this->window->markFired('DNS-001:' . $parent, $ts, self::WINDOW_SECONDS)
            ) {
                $profile = $this->profile($names);
                $corroborated = $profile['mean_entropy'] >= self::CORROBORATION_MEAN_ENTROPY
                    || $profile['digit_share'] >= self::CORROBORATION_DIGIT_SHARE;

                $findings[] = $this->finding(
                    'DNS-001',
                    'Many distinct non-existent names queried under one domain',
                    $corroborated ? 'critical' : 'high',
                    'T1568.002',
                    sprintf(
                        'this host asked for %d distinct names under %s in %ds and every one came '
                        . 'back NXDOMAIN (%s). The leftmost labels average %.2f bits of entropy over '
                        . '%.1f characters and %d%% of them contain digits, %s. Measured on this '
                        . 'host, one parent domain has never produced more than 1 distinct '
                        . 'non-existent name in a window of this length',
                        count($names),
                        $parent,
                        self::WINDOW_SECONDS,
                        $this->sample($names),
                        $profile['mean_entropy'],
                        $profile['mean_length'],
                        (int) round($profile['digit_share'] * 100),
                        $corroborated
                            ? 'which is the shape of generated labels rather than typed ones'
                            : 'which is not obviously generated, so search-domain expansion or a '
                              . 'broken client is also consistent with this',
                    )
                );
            }
        }

        /* DNS-002 - the same shape spread across parent domains -------------
         * A DGA that walks TLDs, or one that uses single-label names, defeats
         * the per-parent count: each name lands in its own group. Measured host
         * wide, this host reached 3 distinct NXDOMAIN names in a window (4 at
         * 900 seconds) across 4 parents in total. */
        if ($isNxdomain) {
            $spread = $this->window->distinctNxdomainHostWide();

            if (count($spread['names']) >= self::NX_DISTINCT_HOST_WIDE
                && count($spread['parents']) >= self::NX_HOST_WIDE_MIN_PARENTS
                // Disjoint from DNS-001 by construction: if any parent holds
                // enough names to trip the per-parent rule, that rule owns the
                // window and this one stays quiet rather than restating it.
                && $spread['largest_parent'] < self::NX_DISTINCT_PER_PARENT
                && $this->window->markFired('DNS-002', $ts, self::WINDOW_SECONDS)
            ) {
                $profile = $this->profile($spread['names']);

                $findings[] = $this->finding(
                    'DNS-002',
                    'Non-existent names queried across many unrelated domains',
                    'high',
                    'T1568.002',
                    sprintf(
                        '%d distinct names under %d different parent domains all came back NXDOMAIN '
                        . 'within %ds (%s). The leftmost labels average %.2f bits of entropy and %d%% '
                        . 'contain digits. Measured on this host the whole window has never held more '
                        . 'than 3 distinct non-existent names, from 4 parents in total. No single '
                        . 'domain here holds more than %d of these names, which is what makes this a '
                        . 'spread across domains rather than one burst under one of them',
                        count($spread['names']),
                        count($spread['parents']),
                        self::WINDOW_SECONDS,
                        $this->sample($spread['names']),
                        $profile['mean_entropy'],
                        (int) round($profile['digit_share'] * 100),
                        $spread['largest_parent']
                    )
                );
            }
        }

        /* DNS-003 - resolution is failing at a rate above baseline ----------
         * Deliberately low, and deliberately separate from the two counting
         * rules, because it is the one signal here that fires on repeated
         * failure of a SMALL set of names: a sinkholed or taken-down C2 domain,
         * or a resolver that has broken. It cannot tell those apart, which is
         * why it corroborates rather than wakes anybody.
         *
         * It is also the rule that refuses to judge. Below the denominator
         * floor there is no answer to give in either direction, so nothing is
         * reported and the refusal is counted in withheld(). */
        $counts = $this->window->answerCounts();

        if ($counts['answers'] < self::NX_RATE_MIN_ANSWERS) {
            $this->withheld['DNS-003'] = ($this->withheld['DNS-003'] ?? 0) + 1;
        } elseif ($counts['nxdomain'] / $counts['answers'] >= self::NX_RATE
            && $this->window->markFired('DNS-003', $ts, self::WINDOW_SECONDS)
        ) {
            $spread = $this->window->distinctNxdomainHostWide();

            $findings[] = $this->finding(
                'DNS-003',
                'Name resolution is failing far more often than this host normally does',
                'low',
                'T1568',
                sprintf(
                    '%d of the last %d answers in %ds were NXDOMAIN (%.0f%%), over %d distinct '
                    . "names. This host's baseline is 2.19%% of answers, and the worst 300s window "
                    . 'measured on real traffic was 8.0%% at this denominator. A small set of names '
                    . 'failing repeatedly is a sinkholed destination or a broken resolver; a large '
                    . 'set is generated names, which DNS-001 and DNS-002 count directly',
                    $counts['nxdomain'],
                    $counts['answers'],
                    self::WINDOW_SECONDS,
                    100 * $counts['nxdomain'] / $counts['answers'],
                    count($spread['names'])
                )
            );
        }

        /* DNS-004 - one algorithmically built label that actually resolved ---
         * The rendezvous name: the one domain out of a generated set that was
         * registered and answered. Restricted to answers carrying an address,
         * because the ones that failed are counted by DNS-001 and because an
         * answer with an address is the point at which the host is about to
         * connect somewhere. Graded medium: it is one name, and its
         * discriminator (digits in the leftmost label) is measured on this host
         * only. */
        $addresses = is_array($dns['addresses'] ?? null) ? $dns['addresses'] : [];

        if ($rcode === 'NOERROR' && $addresses !== []) {
            $features = $this->domainFeatures($name);

            if ($features['label_length'] >= self::DGA_MIN_LABEL_LENGTH
                && $features['digit_ratio'] >= self::DGA_MIN_DIGIT_RATIO
                && $features['entropy'] >= self::DGA_MIN_ENTROPY
                && $this->window->markFired('DNS-004:' . $name, $ts, self::WINDOW_SECONDS)
            ) {
                $findings[] = $this->finding(
                    'DNS-004',
                    'A name with generated structure resolved to an address',
                    'medium',
                    'T1568.002',
                    sprintf(
                        '%s resolved to %s. Its leftmost label is %d characters with %.0f%% digits '
                        . 'and %.2f bits of entropy; measured over 23,338 real DNS rows on this '
                        . 'host, no leftmost label reached a digit ratio of %.1f (the highest was '
                        . '0.167, on the name this host uses to check its own PowerDNS version) and '
                        . 'none met all three conditions',
                        $name,
                        implode(', ', array_slice($addresses, 0, 3)),
                        $features['label_length'],
                        $features['digit_ratio'] * 100,
                        $features['entropy'],
                        self::DGA_MIN_DIGIT_RATIO
                    )
                );
            }
        }

        return $findings;
    }

    /**
     * What the rules had to judge on, so a quiet result can be read correctly.
     *
     * "No finding" from this class means one of two very different things: the
     * window held enough traffic and nothing in it looked like a DGA, or the
     * window held almost nothing. The caller reports this next to the finding
     * count, in the same spirit as `DnsEventNormalizer::rejections()`.
     *
     * @return array{window_seconds:int, observed_span:float, answers:int, nxdomain:int,
     *               distinct_nxdomain:int, parents:int, tracked_names:int, evicted:int,
     *               rate_basis:bool, span_basis:bool, withheld:array<string, int>}
     */
    public function basis(): array
    {
        $counts = $this->window->answerCounts();
        $spread = $this->window->distinctNxdomainHostWide();

        return [
            'window_seconds' => self::WINDOW_SECONDS,
            'observed_span' => $this->window->observedSpan(),
            'answers' => $counts['answers'],
            'nxdomain' => $counts['nxdomain'],
            'distinct_nxdomain' => count($spread['names']),
            'parents' => count($spread['parents']),
            'tracked_names' => $this->window->trackedNames(),
            'evicted' => $this->window->evicted(),
            // Whether DNS-003 had a denominator to divide by at all.
            'rate_basis' => $counts['answers'] >= self::NX_RATE_MIN_ANSWERS,
            // Whether the window actually covers the period the thresholds were
            // measured over. False means the counting rules can only
            // under-report, which is safe for a positive finding and useless as
            // a negative one.
            'span_basis' => $this->window->observedSpan() >= self::WINDOW_SECONDS,
            'withheld' => $this->withheld,
        ];
    }

    /** @return array<string, int> */
    public function withheld(): array
    {
        return $this->withheld;
    }

    public function resetWithheld(): void
    {
        $this->withheld = [];
    }

    /**
     * The domain a set of names is grouped under.
     *
     * Two labels, or three where the last two are a known two-part public
     * suffix. A single-label name is its own parent: `nginx-proxy` is a real
     * query this host makes (64 NXDOMAIN answers in the corpus) and it has no
     * parent, so it groups alone, which is also why DNS-002 exists.
     */
    public function parentDomain(string $name): string
    {
        $labels = explode('.', trim($name, '.'));
        $count = count($labels);

        if ($count <= 2) {
            return implode('.', $labels);
        }

        $lastTwo = implode('.', array_slice($labels, -2));

        if (in_array($lastTwo, self::MULTI_PART_SUFFIXES, true)) {
            return implode('.', array_slice($labels, -3));
        }

        return $lastTwo;
    }

    /**
     * Features of the leftmost label, which is the part a DGA generates.
     *
     * Shannon entropy is computed over bytes of that label only. Doing it over
     * the whole name would drown the signal: the shared suffix is the same on
     * every name in a burst, so a 12-character generated label under
     * `.dyndns.org` scores much the same as `redirector.gvt1.com`.
     *
     * @return array{leftmost:string, label_length:int, entropy:float, digit_ratio:float,
     *               label_count:int, name_length:int}
     */
    public function domainFeatures(string $name): array
    {
        $labels = explode('.', trim($name, '.'));
        $leftmost = $labels[0] ?? '';
        $length = strlen($leftmost);
        $digits = strlen((string) preg_replace('/[^0-9]/', '', $leftmost));

        return [
            'leftmost' => $leftmost,
            'label_length' => $length,
            'entropy' => $this->entropy($leftmost),
            'digit_ratio' => $length > 0 ? $digits / $length : 0.0,
            'label_count' => count($labels),
            'name_length' => strlen($name),
        ];
    }

    /**
     * Shannon entropy of a string in bits per character.
     *
     * Bounded above by log2(strlen($value)), which is the reason this is never
     * a trigger on its own: the bound means the same numeric threshold means
     * different things on a 6-character label and a 30-character one.
     */
    public function entropy(string $value): float
    {
        $length = strlen($value);

        if ($length === 0) {
            return 0.0;
        }

        $bits = 0.0;

        foreach (count_chars($value, 1) as $occurrences) {
            $p = $occurrences / $length;
            $bits -= $p * log($p, 2);
        }

        return $bits;
    }

    /**
     * The aggregate shape of a set of names, for corroboration.
     *
     * @param array<int, string> $names
     * @return array{mean_entropy:float, mean_length:float, digit_share:float}
     */
    private function profile(array $names): array
    {
        if ($names === []) {
            return ['mean_entropy' => 0.0, 'mean_length' => 0.0, 'digit_share' => 0.0];
        }

        $entropy = 0.0;
        $length = 0;
        $withDigits = 0;

        foreach ($names as $name) {
            $features = $this->domainFeatures($name);
            $entropy += $features['entropy'];
            $length += $features['label_length'];

            if ($features['digit_ratio'] >= self::DGA_MIN_DIGIT_RATIO) {
                $withDigits++;
            }
        }

        $count = count($names);

        return [
            'mean_entropy' => $entropy / $count,
            'mean_length' => $length / $count,
            'digit_share' => $withDigits / $count,
        ];
    }

    /**
     * A few of the names, for the reason string.
     *
     * Truncated because the whole set can be hundreds of names and this string
     * ends up in an alert payload; the count is already stated separately, so
     * the sample is evidence rather than the finding itself.
     *
     * @param array<int, string> $names
     */
    private function sample(array $names, int $limit = 4): string
    {
        sort($names);
        $shown = array_slice($names, 0, $limit);
        $suffix = count($names) > $limit ? ', ...' : '';

        return implode(', ', $shown) . $suffix;
    }

    /**
     * The event's own time, in seconds with the logged fraction.
     *
     * `network.event_time_wall` is the DNS-only precise field
     * `DnsEventNormalizer` adds; `ts` is the same instant truncated to a whole
     * second. Falling back to `time()` is deliberately not done: it would make
     * a replay of stored events judge them against the current clock, and every
     * window would come out empty.
     */
    private function eventTime(array $event): float
    {
        $net = is_array($event['network'] ?? null) ? $event['network'] : [];
        $wall = $net['event_time_wall'] ?? null;

        if (is_float($wall) || is_int($wall)) {
            return (float) $wall;
        }

        return (float) ($event['ts'] ?? 0);
    }

    private function finding(string $rule, string $name, string $severity, string $mitre, string $reason): array
    {
        return [
            'rule' => $rule,
            'name' => $name,
            'severity' => $severity,
            'mitre' => $mitre,
            'reason' => $reason,
        ];
    }

    /**
     * What these rules declined to judge, and why.
     *
     * Surfaced so a coverage report can say "silent because it excluded 412
     * reverse lookups" rather than just "silent".
     *
     * @return array{reverse:int, reduced:int}
     */
    public function exclusions(): array
    {
        return ['reverse' => $this->excludedReverse, 'reduced' => $this->reducedReverse];
    }
}
