<?php

namespace Tests\Unit;

use App\Services\Network\DnsAnomalyRules;
use App\Services\Network\DnsEventNormalizer;
use App\Services\Network\DnsResolutionWindow;
use App\Services\Network\NetworkBaselineStore;
use App\Services\Network\NetworkRuleEngine;
use DateTimeImmutable;
use DateTimeZone;
use Tests\TestCase;

/**
 * The DGA rules, proved in both directions.
 *
 * Both directions, because either one alone is worthless. A detector that has
 * only been shown to fire might fire on everything, and a detector that has
 * only been shown to be quiet might be incapable of firing at all, which is the
 * worse failure: the coverage still appears on the rule list.
 *
 * The negative direction is replayed over this host's real DNS traffic from
 * /var/log/suricata/eve.json rather than over invented "clean" events, because
 * invented traffic agrees with whatever the rule already assumes. It caught the
 * fact that the highest-entropy name in this host's entire DNS history is
 * generated by this project's own test suite.
 *
 * Every synthetic event below is a real log line with one or two members
 * replaced, so everything the rules read except the name and the clock is real.
 */
class DnsAnomalyRulesTest extends TestCase
{
    /** A real NXDOMAIN answer. 181 of the 255 NXDOMAIN answers in the corpus. */
    private const ANSWER_DOCKER_NXDOMAIN = '{"timestamp":"2026-08-28T23:05:33.655885+0800","flow_id":1644109239592472,"event_type":"dns","src_ip":"192.168.1.114","src_port":34204,"dest_ip":"8.8.8.8","dest_port":53,"proto":"UDP","pkt_src":"wire/pcap","dns":{"version":2,"type":"answer","id":38508,"flags":"8183","qr":true,"rd":true,"ra":true,"opcode":0,"rrname":"host.docker.internal","rrtype":"A","rcode":"NXDOMAIN","authorities":[{"rrname":"","rrtype":"SOA","ttl":86399,"soa":{"mname":"a.root-servers.net","rname":"nstld.verisign-grs.com","serial":2026082800,"refresh":1800,"retry":900,"expire":604800,"minimum":86400}}]}}';

    /** A real single-label NXDOMAIN: a Docker service name, 64 answers. */
    private const ANSWER_NGINX_PROXY_NXDOMAIN = '{"timestamp":"2026-08-28T23:06:15.411747+0800","flow_id":2020778053971253,"event_type":"dns","src_ip":"192.168.1.114","src_port":36505,"dest_ip":"8.8.8.8","dest_port":53,"proto":"UDP","pkt_src":"wire/pcap","dns":{"version":2,"type":"answer","id":32507,"flags":"8183","qr":true,"rd":true,"ra":true,"opcode":0,"rrname":"nginx-proxy","rrtype":"A","rcode":"NXDOMAIN","authorities":[{"rrname":"","rrtype":"SOA","ttl":86380,"soa":{"mname":"a.root-servers.net","rname":"nstld.verisign-grs.com","serial":2026082800,"refresh":1800,"retry":900,"expire":604800,"minimum":86400}}]}}';

    /**
     * The highest leftmost-label entropy in this host's whole DNS history:
     * 3.88 bits over 22 characters, with digits in it, and NXDOMAIN. It is
     * ours. tests/Unit/NetworkContainmentTest.php asks the containment code to
     * resolve this name, and the lookup goes out on the wire. Any single-name
     * entropy rule set low enough to catch real DGA fires on this.
     */
    private const ANSWER_OWN_TEST_PROBE = '{"timestamp":"2026-08-28T23:08:59.774562+0800","flow_id":1038105406995138,"event_type":"dns","src_ip":"192.168.1.114","src_port":53194,"dest_ip":"8.8.8.8","dest_port":53,"proto":"UDP","pkt_src":"wire/pcap","dns":{"version":2,"type":"answer","id":2358,"flags":"8183","qr":true,"rd":true,"ra":true,"opcode":0,"rrname":"no-such-host-abc123xyz.invalid","rrtype":"A","rcode":"NXDOMAIN","authorities":[{"rrname":"","rrtype":"SOA","ttl":86351,"soa":{"mname":"a.root-servers.net","rname":"nstld.verisign-grs.com","serial":2026082800,"refresh":1800,"retry":900,"expire":604800,"minimum":86400}}]}}';

    /** A real answer that resolved, for the rules that need an address. */
    private const ANSWER_GITHUB_RESOLVED = '{"timestamp":"2026-08-28T23:05:29.813420+0800","flow_id":371385289636133,"event_type":"dns","src_ip":"192.168.1.114","src_port":43489,"dest_ip":"8.8.8.8","dest_port":53,"proto":"UDP","pkt_src":"wire/pcap","dns":{"version":2,"type":"answer","id":858,"flags":"8180","qr":true,"rd":true,"ra":true,"opcode":0,"rrname":"api.github.com","rrtype":"A","rcode":"NOERROR","answers":[{"rrname":"api.github.com","rrtype":"A","ttl":23,"rdata":"20.27.177.116"}],"grouped":{"A":["20.27.177.116"]}}}';

    private const LIVE_LOG = '/var/log/suricata/eve.json';

    /** A fixed instant inside the measured corpus, so nothing depends on now(). */
    private const T0 = 1787929529.0;

    private DnsEventNormalizer $normalizer;
    private DnsAnomalyRules $rules;

    /** Kept so a test can assert what the rules had to work with, not just what they said. */
    private DnsResolutionWindow $window;

    protected function setUp(): void
    {
        parent::setUp();

        $this->normalizer = new DnsEventNormalizer();
        $this->window = new DnsResolutionWindow();
        $this->rules = new DnsAnomalyRules($this->window);
    }

    /* ------------------------------------------------------------------ */
    /* The negative direction, on real traffic                             */
    /* ------------------------------------------------------------------ */

    /**
     * Replayed over this host's live DNS log: not one finding.
     *
     * The same pass re-measures the two facts the thresholds were set from, so
     * the margin is asserted rather than remembered: no parent domain reaches
     * more than a couple of distinct NXDOMAIN names in a window, and neither
     * does the host as a whole.
     *
     * Skipped rather than failed when the log cannot supply 20,000 rows,
     * because "we could not look" is a different result from "there was nothing
     * there", and the skip message says which one happened.
     */
    public function test_it_is_silent_on_twenty_thousand_real_dns_events(): void
    {
        $lines = $this->liveDnsLines();

        if (count($lines) < 20000) {
            $this->markTestSkipped(
                'not enough live DNS telemetry to judge silence: ' . count($lines)
                . ' rows in the tail of ' . self::LIVE_LOG . ', 20000 required'
            );
        }

        $window = new DnsResolutionWindow();
        $rules = new DnsAnomalyRules($window);

        $answers = 0;
        $nxdomain = 0;
        $findings = [];
        $maxPerParent = 0;
        $maxHostWide = 0;

        foreach ($lines as $line) {
            $event = $this->normalizer->normalizeLine($line);

            if ($event === null) {
                continue;
            }

            foreach ($rules->evaluate($event) as $finding) {
                $findings[] = $finding['rule'] . ' ' . $finding['reason'];
            }

            if (($event['dns']['type'] ?? '') !== 'answer') {
                continue;
            }

            $answers++;

            if (($event['dns']['rcode'] ?? '') !== 'NXDOMAIN') {
                continue;
            }

            $nxdomain++;
            $parent = $rules->parentDomain($event['dns']['rrname']);
            $maxPerParent = max($maxPerParent, count($window->distinctNxdomainNames($parent)));
            $maxHostWide = max($maxHostWide, count($window->distinctNxdomainHostWide()['names']));
        }

        // Reported in the failure message rather than kept quiet, so a
        // regression says how much traffic it took to produce and which rule
        // it was.
        $this->assertSame(
            [],
            $findings,
            sprintf(
                'false positives over %d real rows (%d answers, %d NXDOMAIN): %s',
                count($lines),
                $answers,
                $nxdomain,
                implode(' | ', array_slice($findings, 0, 5))
            )
        );

        $this->assertGreaterThan(5000, $answers, 'the replay has to contain answers to have judged anything');
        $this->assertGreaterThan(0, $nxdomain, 'and NXDOMAIN answers, or the primary rule was never exercised');

        // The measurement the DNS-001 threshold of 12 was set from. Measured at
        // the time of writing: 1, at every window length from 60s to 900s.
        $this->assertLessThan(
            12,
            $maxPerParent,
            "a real parent domain reached {$maxPerParent} distinct NXDOMAIN names in a 300s window"
        );

        // And the DNS-002 threshold of 18. Measured: 3 in a 300s window.
        $this->assertLessThan(
            18,
            $maxHostWide,
            "real traffic reached {$maxHostWide} distinct NXDOMAIN names host wide in a 300s window"
        );

        $this->assertSame([], $this->normalizer->rejections(), 'real rows must not be rejected');
    }

    /**
     * Why entropy is not the trigger, asserted against the live log.
     *
     * This host's own traffic contains a name whose leftmost label clears the
     * entropy floor these rules use for corroboration, so an entropy trigger
     * would have fired on real traffic; nothing in the corpus meets the
     * conjunction DNS-004 actually uses.
     */
    public function test_entropy_alone_would_fire_on_real_traffic_and_the_conjunction_does_not(): void
    {
        $lines = $this->liveDnsLines();

        if ($lines === []) {
            $this->markTestSkipped('no live DNS telemetry to measure entropy against');
        }

        $names = [];

        foreach ($lines as $line) {
            $event = $this->normalizer->normalizeLine($line);

            if ($event !== null) {
                $names[$event['dns']['rrname']] = true;
            }
        }

        $entropyHits = [];
        $conjunctionHits = [];

        foreach (array_keys($names) as $name) {
            $features = $this->rules->domainFeatures((string) $name);

            if ($features['entropy'] >= 3.0) {
                $entropyHits[] = $name;
            }

            if ($features['entropy'] >= 3.0
                && $features['digit_ratio'] >= 0.2
                && $features['label_length'] >= 12
            ) {
                $conjunctionHits[] = $name;
            }
        }

        $this->assertNotSame(
            [],
            $entropyHits,
            'if no real name clears 3.0 bits then this host cannot demonstrate the problem any more'
        );

        $this->assertSame(
            [],
            $conjunctionHits,
            'the conjunction must be clean on real names: ' . implode(', ', $conjunctionHits)
        );
    }

    /**
     * The single loudest real name, on its own.
     *
     * 3.88 bits over 22 characters with digits in it, refused by the resolver
     * eight times, and generated by this repository's own test suite. It must
     * produce nothing: one name repeated is one distinct name.
     */
    public function test_our_own_test_suites_probe_is_silent(): void
    {
        $findings = [];

        for ($i = 0; $i < 8; $i++) {
            $event = $this->real(self::ANSWER_OWN_TEST_PROBE, self::T0 + ($i * 30));
            $findings = array_merge($findings, $this->rules->evaluate($event));
        }

        $this->assertSame([], $findings);

        // And the reason it is silent is the count, not the shape: this name is
        // above every corroborating threshold in the file.
        $features = $this->rules->domainFeatures('no-such-host-abc123xyz.invalid');
        $this->assertGreaterThan(3.5, $features['entropy']);
        $this->assertGreaterThan(0.1, $features['digit_ratio']);
        $this->assertGreaterThan(20, $features['label_length']);
    }

    /**
     * The repeated NXDOMAIN set this host really produces, at the worst share
     * ever measured on it.
     *
     * 181 refusals of one Docker hostname and 64 of one container service name
     * is 96% of the NXDOMAIN in the corpus. Here they are replayed as 8.3% of a
     * stream of answers, which is above the worst 300-second window measured on
     * real traffic (8.0% at a denominator of 50 or more, against a baseline of
     * 2.19%), and nothing fires: a rate rule reads this as constant failure, a
     * distinct-count rule reads it as two names.
     */
    public function test_the_hosts_own_repeated_nxdomain_set_is_silent(): void
    {
        $findings = [];
        $nxdomain = 0;

        for ($i = 0; $i < 3060; $i++) {
            // One in twelve, which is 8.3%, alternating the two names this host
            // really fails to resolve.
            if ($i % 12 === 0) {
                $line = $nxdomain % 3 === 0
                    ? self::ANSWER_NGINX_PROXY_NXDOMAIN
                    : self::ANSWER_DOCKER_NXDOMAIN;
                $nxdomain++;
                $event = $this->real($line, self::T0 + ($i * 0.25));
            } else {
                $event = $this->resolved('api.github.com', self::T0 + ($i * 0.25), '20.27.177.116');
            }

            $findings = array_merge($findings, $this->rules->evaluate($event));
        }

        $this->assertSame([], $findings);
        $this->assertSame(255, $nxdomain, 'the corpus NXDOMAIN volume, all of it in two names');
        $this->assertSame(2, $this->rules->basis()['distinct_nxdomain']);
    }

    /**
     * What the same two names do when literally nothing else resolves.
     *
     * Not a shape this host produces (measured, the worst 300-second window is
     * 8.0% NXDOMAIN), but worth pinning down because it is the boundary between
     * the two kinds of rule in this file. The counting rules stay silent, since
     * two names repeated a hundred times is still two names, and only the rate
     * rule speaks, which is exactly what it is for: a resolver answering
     * nothing but NXDOMAIN is broken, or the destination has been sinkholed.
     * It is graded low because it cannot tell those two apart.
     */
    public function test_a_pure_nxdomain_stream_is_a_rate_finding_and_not_a_dga_finding(): void
    {
        $findings = [];

        for ($i = 0; $i < 120; $i++) {
            $line = $i % 3 === 0 ? self::ANSWER_NGINX_PROXY_NXDOMAIN : self::ANSWER_DOCKER_NXDOMAIN;
            $findings = array_merge($findings, $this->rules->evaluate($this->real($line, self::T0 + ($i * 1.5))));
        }

        $this->assertSame(['DNS-003'], array_column($findings, 'rule'));
        $this->assertStringContainsString('100%', $findings[0]['reason']);
        $this->assertStringContainsString('over 2 distinct names', $findings[0]['reason']);
    }

    /* ------------------------------------------------------------------ */
    /* The positive direction                                              */
    /* ------------------------------------------------------------------ */

    /**
     * A synthetic DGA burst: 30 distinct 12-character labels under one parent,
     * every one NXDOMAIN, 1.7 seconds apart.
     *
     * Three things are asserted, not one. It fires; it fires on the twelfth
     * name rather than the thirtieth, so the threshold is where the docblock
     * says it is; and it fires ONCE, because the governor cannot deduplicate
     * DNS findings (its signature is built from username, binary and command
     * line, all empty here) and nineteen copies of one burst is how a rule gets
     * switched off.
     */
    public function test_it_fires_once_on_a_synthetic_dga_burst_under_one_parent(): void
    {
        $fired = [];

        foreach ($this->dgaLabels(30, 12, 4242) as $index => $label) {
            foreach ($this->rules->evaluate(
                $this->real(self::ANSWER_DOCKER_NXDOMAIN, self::T0 + ($index * 1.7), $label . '.dga-example.com')
            ) as $finding) {
                $fired[] = ['index' => $index, 'finding' => $finding];
            }
        }

        $this->assertCount(1, $fired, 'one burst is one finding');
        $this->assertSame(11, $fired[0]['index'], 'the twelfth distinct name is the threshold');

        $finding = $fired[0]['finding'];
        $this->assertSame('DNS-001', $finding['rule']);
        $this->assertSame('critical', $finding['severity'], 'generated labels corroborate the count');
        $this->assertSame('T1568.002', $finding['mitre']);
        $this->assertStringContainsString('12 distinct names under dga-example.com', $finding['reason']);
        $this->assertStringContainsString('NXDOMAIN', $finding['reason']);
    }

    /**
     * A burst under one parent is one finding on a real host too, not two.
     *
     * The burst test above is clean: one parent, nothing else in the window. A
     * real host is not. This one's everyday NXDOMAIN traffic is two names —
     * a Docker hostname and the container service name `nginx-proxy`, together
     * 96% of the corpus NXDOMAIN — under two different parents, because a
     * single-label name is its own parent. So a burst under one parent arrived
     * with two of DNS-002's three required parents already in the window, and
     * DNS-002 fired alongside DNS-001 saying the same thing less specifically.
     *
     * That matters beyond tidiness. A responder who sees two rules agree reads
     * it as two pieces of evidence, and the second one names no parent, so it
     * is the less actionable of the two. The conditions are now disjoint: if
     * any parent holds enough names for the per-parent rule, that rule owns the
     * window.
     */
    public function test_a_single_parent_burst_beside_real_background_fires_only_the_per_parent_rule(): void
    {
        $fired = [];

        // The background this host really produces, repeated the way it really
        // is: two names, two parents, many answers.
        for ($i = 0; $i < 20; $i++) {
            $line = $i % 2 === 0 ? self::ANSWER_DOCKER_NXDOMAIN : self::ANSWER_NGINX_PROXY_NXDOMAIN;

            foreach ($this->rules->evaluate($this->real($line, self::T0 + $i * 0.4)) as $finding) {
                $fired[] = $finding;
            }
        }

        $this->assertSame([], $fired, 'the background alone is not a finding');

        foreach ($this->dgaLabels(24, 12, 90210) as $index => $label) {
            foreach ($this->rules->evaluate(
                $this->real(self::ANSWER_DOCKER_NXDOMAIN, self::T0 + 10.0 + ($index * 1.7), $label . '.dga-example.com')
            ) as $finding) {
                $fired[] = $finding;
            }
        }

        $rules = array_map(static fn (array $f): string => $f['rule'], $fired);

        $this->assertSame(['DNS-001'], $rules, 'one burst, one rule, and it is the one that names the parent');

        // The host-wide count really was over its own threshold, so the rule
        // stayed quiet by the disjointness condition rather than for want of
        // material: 24 generated names plus the two background ones.
        $spread = $this->window->distinctNxdomainHostWide();
        $this->assertGreaterThanOrEqual(18, count($spread['names']));
        $this->assertGreaterThanOrEqual(3, count($spread['parents']));
        $this->assertGreaterThanOrEqual(12, $spread['largest_parent']);
    }

    /**
     * The same burst spread across parent domains.
     *
     * 24 names over 4 parents, 6 each, so no parent reaches the DNS-001
     * threshold. This is a DGA that walks TLDs, and the per-parent count cannot
     * see it.
     */
    public function test_a_burst_spread_across_parents_fires_the_host_wide_rule(): void
    {
        $fired = [];
        $index = 0;

        foreach (['a-example.com', 'b-example.net', 'c-example.org', 'd-example.info'] as $parent) {
            foreach ($this->dgaLabels(6, 12, 11 + $index) as $label) {
                foreach ($this->rules->evaluate(
                    $this->real(self::ANSWER_DOCKER_NXDOMAIN, self::T0 + ($index * 2.0), $label . '.' . $parent)
                ) as $finding) {
                    $fired[] = ['index' => $index, 'finding' => $finding];
                }

                $index++;
            }
        }

        $this->assertCount(1, $fired);
        $this->assertSame('DNS-002', $fired[0]['finding']['rule']);
        $this->assertSame('high', $fired[0]['finding']['severity']);
        $this->assertSame(17, $fired[0]['index'], 'the eighteenth distinct name is the threshold');

        // Three parents, not four: the eighteenth name arrives while the fourth
        // parent has not been queried yet, which is the rule firing as early as
        // its own conditions allow rather than waiting for a rounder number.
        $this->assertStringContainsString('3 different parent domains', $fired[0]['finding']['reason']);
    }

    /**
     * Single-label generated names, which have no parent to group under.
     *
     * Every name is its own parent, so DNS-001 can never see them. It is not a
     * hypothetical shape: this host really does resolve single-label names
     * (`nginx-proxy`, 64 refusals), which is why the normaliser flags them
     * instead of dropping them.
     */
    public function test_single_label_generated_names_are_caught_host_wide(): void
    {
        $fired = [];

        foreach ($this->dgaLabels(20, 12, 12) as $index => $label) {
            foreach ($this->rules->evaluate(
                $this->real(self::ANSWER_NGINX_PROXY_NXDOMAIN, self::T0 + ($index * 2.0), $label)
            ) as $finding) {
                $fired[] = $finding;
            }
        }

        $this->assertCount(1, $fired);
        $this->assertSame('DNS-002', $fired[0]['rule']);
    }

    /**
     * An alphabetic-only DGA, which is Conficker's shape.
     *
     * It must still fire, because the trigger is the count and the count does
     * not care what alphabet the names use. And it must NOT be escalated to
     * critical: with no digits and a lower mean entropy there is nothing to
     * corroborate with, and search-domain expansion or a broken client is also
     * consistent with what was seen. Saying so in the finding is the point.
     */
    public function test_an_alphabetic_only_dga_fires_but_is_not_escalated(): void
    {
        $fired = [];

        foreach ($this->dgaLabels(30, 10, 7, 'abcdefghijklmnopqrstuvwxyz') as $index => $label) {
            foreach ($this->rules->evaluate(
                $this->real(self::ANSWER_DOCKER_NXDOMAIN, self::T0 + ($index * 1.5), $label . '.ws-example.net')
            ) as $finding) {
                $fired[] = $finding;
            }
        }

        $this->assertCount(1, $fired);
        $this->assertSame('DNS-001', $fired[0]['rule']);
        $this->assertSame('high', $fired[0]['severity']);
        $this->assertStringContainsString('0% of them contain digits', $fired[0]['reason']);
        $this->assertStringContainsString('not obviously generated', $fired[0]['reason']);
    }

    /**
     * A generated name that actually resolved: the rendezvous.
     *
     * Reported once per name per window, for the same reason as the burst: a
     * name is re-resolved every time its TTL expires (measured on this host,
     * the median answer TTL is 144 seconds), so without the cooldown one C2
     * domain would produce a finding every couple of minutes forever.
     */
    public function test_a_generated_name_that_resolved_is_reported_once(): void
    {
        $first = $this->rules->evaluate($this->resolved('a7f3k92m1x8q.rendezvous-example.com', self::T0));
        $again = $this->rules->evaluate($this->resolved('a7f3k92m1x8q.rendezvous-example.com', self::T0 + 150));

        $this->assertCount(1, $first);
        $this->assertSame('DNS-004', $first[0]['rule']);
        $this->assertSame('medium', $first[0]['severity']);
        $this->assertStringContainsString('185.199.108.153', $first[0]['reason']);
        $this->assertSame([], $again, 'the same name inside the window is the same fact');

        // The name that failed is DNS-001's business, not this rule's: an
        // answer with no address is not a host about to connect anywhere.
        $rules = new DnsAnomalyRules(new DnsResolutionWindow());
        $this->assertSame([], $rules->evaluate(
            $this->real(self::ANSWER_DOCKER_NXDOMAIN, self::T0, 'a7f3k92m1x8q.rendezvous-example.com')
        ));
    }

    /* ------------------------------------------------------------------ */
    /* Refusing to judge, and the window                                   */
    /* ------------------------------------------------------------------ */

    /**
     * The rate rule has no answer without a denominator, and says so.
     *
     * Twenty answers of which nineteen are NXDOMAIN is 95%, which is far above
     * every threshold in the file, and it is still not a judgement: the
     * measured minimum number of answers in a trailing 300-second window on
     * this host is 1, where a single refused Docker hostname reads as 100%.
     * The refusal is counted so that a quiet result cannot be mistaken for a
     * clean one.
     */
    public function test_the_rate_rule_refuses_to_judge_without_a_denominator(): void
    {
        for ($i = 0; $i < 19; $i++) {
            $this->assertSame([], $this->rules->evaluate(
                $this->real(self::ANSWER_DOCKER_NXDOMAIN, self::T0 + $i)
            ));
        }

        $this->assertSame([], $this->rules->evaluate($this->resolved('api.github.com', self::T0 + 20)));

        $basis = $this->rules->basis();

        $this->assertFalse($basis['rate_basis'], 'twenty answers is not a denominator');
        $this->assertSame(20, $basis['answers']);
        $this->assertSame(20, $basis['withheld']['DNS-003'], 'every withheld judgement is counted');
        $this->assertSame($this->rules->withheld(), $basis['withheld']);
    }

    /**
     * With a denominator, repeated failure of a small set is reported low.
     *
     * This is the shape the distinct-count rules deliberately cannot see: one
     * name failing over and over, which is a sinkholed destination or a broken
     * resolver rather than a generation algorithm. Graded low because it cannot
     * tell those apart.
     */
    public function test_the_rate_rule_fires_on_a_small_set_failing_repeatedly(): void
    {
        $fired = [];

        for ($i = 0; $i < 100; $i++) {
            $event = $i % 2 === 0
                ? $this->real(self::ANSWER_DOCKER_NXDOMAIN, self::T0 + ($i * 2.0), 'sinkholed.example.com')
                : $this->resolved('api.github.com', self::T0 + ($i * 2.0));

            foreach ($this->rules->evaluate($event) as $finding) {
                $fired[] = ['index' => $i, 'finding' => $finding];
            }
        }

        $this->assertCount(1, $fired);
        $this->assertSame('DNS-003', $fired[0]['finding']['rule']);
        $this->assertSame('low', $fired[0]['finding']['severity']);
        $this->assertSame(49, $fired[0]['index'], 'it waits for the fiftieth answer, then divides');
        $this->assertStringContainsString('1 distinct', $fired[0]['finding']['reason']);
        $this->assertSame(1, $this->rules->basis()['distinct_nxdomain']);
    }

    /**
     * The window has to be carried across the collection cycle, and this is
     * what happens when it is not.
     *
     * Measured on this host, `ids:sync-edr` runs in a fresh PHP process every
     * 30 seconds (security-one-watchdog.sh, EDR_INTERVAL=30). A burst of 30
     * names arriving three per cycle therefore never reaches a threshold inside
     * one process, and the rule silently cannot fire, which is the exact
     * failure mode NET-003 was fixed for. Exporting and restoring the window
     * makes the same traffic alert in the fourth cycle.
     */
    public function test_a_burst_thinner_than_one_cycle_needs_the_window_carried(): void
    {
        $labels = $this->dgaLabels(30, 12, 21);

        $withoutCarrying = $this->replayInCycles($labels, false);
        $withCarrying = $this->replayInCycles($labels, true);

        $this->assertSame([], $withoutCarrying, 'three names per 30s process cannot reach 12 in one process');
        $this->assertCount(1, $withCarrying);
        $this->assertSame('DNS-001', $withCarrying[0]['rule']);
    }

    /** The window is small enough to persist, measured rather than assumed. */
    public function test_the_window_state_is_small_enough_to_carry(): void
    {
        foreach ($this->dgaLabels(30, 12, 3) as $index => $label) {
            $this->rules->evaluate(
                $this->real(self::ANSWER_DOCKER_NXDOMAIN, self::T0 + ($index * 2.0), $label . '.dga-example.com')
            );
        }

        $state = $this->rules->window()->export();
        $encoded = json_encode($state);

        $this->assertIsString($encoded);
        $this->assertLessThan(16384, strlen($encoded), 'a window that cannot be persisted cheaply will not be');

        // Restoring must reproduce the counts, or carrying it across a cycle
        // would quietly lose the burst it exists to remember.
        $restored = new DnsResolutionWindow();
        $restored->restore(json_decode($encoded, true));

        $this->assertSame(
            count($this->rules->window()->distinctNxdomainHostWide()['names']),
            count($restored->distinctNxdomainHostWide()['names'])
        );
        $this->assertSame($this->rules->window()->answerCounts(), $restored->answerCounts());

        // And the cooldown must survive with it, or the first event of the next
        // cycle re-reports the burst the previous cycle already reported.
        $this->assertFalse($restored->markFired('DNS-001:dga-example.com', $this->rules->window()->clock(), 300));
    }

    /**
     * Names age out of the window, so a slow trickle is not a burst.
     *
     * Twelve distinct names spread over an hour is not the same event as twelve
     * in five minutes, and the only thing that separates them is pruning.
     */
    public function test_names_older_than_the_window_are_not_counted(): void
    {
        $findings = [];

        foreach ($this->dgaLabels(30, 12, 5) as $index => $label) {
            // 200 seconds apart, so no two names are ever inside one window
            // together for long enough to accumulate twelve.
            $findings = array_merge($findings, $this->rules->evaluate(
                $this->real(self::ANSWER_DOCKER_NXDOMAIN, self::T0 + ($index * 200.0), $label . '.dga-example.com')
            ));
        }

        $this->assertSame([], $findings);
        $this->assertLessThan(3, $this->rules->basis()['distinct_nxdomain'], 'the window has to forget');
    }

    /**
     * A second burst after the window has rolled is a second finding.
     *
     * The cooldown suppresses copies of one burst, not a recurrence. A DGA that
     * runs on a schedule would otherwise be reported once and never again.
     */
    public function test_a_later_burst_is_reported_again(): void
    {
        $findings = [];

        foreach ([0.0, 900.0] as $offset) {
            foreach ($this->dgaLabels(14, 12, (int) $offset + 1) as $index => $label) {
                $findings = array_merge($findings, $this->rules->evaluate(
                    $this->real(
                        self::ANSWER_DOCKER_NXDOMAIN,
                        self::T0 + $offset + ($index * 1.5),
                        $label . '.dga-example.com'
                    )
                ));
            }
        }

        $this->assertCount(2, $findings);
        $this->assertSame(['DNS-001', 'DNS-001'], array_column($findings, 'rule'));
    }

    /* ------------------------------------------------------------------ */
    /* Shape and grouping                                                  */
    /* ------------------------------------------------------------------ */

    /**
     * A finding from this file must be readable by everything that already
     * consumes network findings.
     *
     * Compared against a finding the existing engine really produced rather
     * than a hand-written key list, because a key list in a test drifts from
     * the real shape without failing.
     */
    public function test_findings_carry_the_network_rule_engine_shape(): void
    {
        $engine = new NetworkRuleEngine(new NetworkBaselineStore(
            sys_get_temp_dir() . '/m11-shape-check-' . getmypid() . '.sqlite'
        ));

        $reference = $engine->evaluate([
            'action' => 'net_connect',
            'path' => '/usr/bin/curl',
            'username' => 'root',
            'network' => [
                'remote_address' => '203.0.113.10',
                'remote_port' => 4444,
                'scope' => 'external',
                'intervals' => [],
            ],
        ]);

        $this->assertNotSame([], $reference, 'the reference rule must have fired for this to compare anything');

        $mine = $this->rules->evaluate($this->resolved('a7f3k92m1x8q.rendezvous-example.com', self::T0));

        $this->assertNotSame([], $mine);
        $this->assertSame(array_keys($reference[0]), array_keys($mine[0]));
    }

    /**
     * Grouping, including the case that is measured at zero today.
     *
     * The two-part suffix list fires on nothing in the corpus. It exists
     * because .tw traffic does appear (`sp.spx.shopee.tw`) and this product's
     * customers are Taiwanese, so `com.tw` is the realistic first arrival, and
     * without it every unrelated com.tw domain would share one group.
     */
    public function test_parent_grouping(): void
    {
        $this->assertSame('github.com', $this->rules->parentDomain('api.github.com'));
        $this->assertSame('github.com', $this->rules->parentDomain('github.com'));
        $this->assertSame('docker.internal', $this->rules->parentDomain('host.docker.internal'));
        $this->assertSame('shopee.tw', $this->rules->parentDomain('sp.spx.shopee.tw'));
        $this->assertSame('nginx-proxy', $this->rules->parentDomain('nginx-proxy'));
        $this->assertSame('example.com.tw', $this->rules->parentDomain('a.b.example.com.tw'));
        $this->assertSame(
            'powerdns.com',
            $this->rules->parentDomain('auth-4.8.5.security-status.secpoll.powerdns.com')
        );
    }

    /**
     * Entropy is bounded by log2(length), which is the reason it is never a
     * trigger: the same number means different things at different lengths.
     */
    public function test_entropy_is_length_bounded(): void
    {
        $this->assertEqualsWithDelta(0.0, $this->rules->entropy('aaaa'), 0.0001);
        $this->assertEqualsWithDelta(2.0, $this->rules->entropy('abcd'), 0.0001);
        $this->assertLessThanOrEqual(log(6, 2), $this->rules->entropy('abcdef'));
        $this->assertSame(0.0, $this->rules->entropy(''));

        // Measured on this host: the leftmost label of nginx-proxy carries
        // 3.096 bits, which is 90% of its own 3.459-bit ceiling.
        $this->assertEqualsWithDelta(3.096, $this->rules->entropy('nginx-proxy'), 0.001);
    }

    /** A query has no rcode, so it can be neither counted nor judged. */
    public function test_queries_and_foreign_events_are_ignored(): void
    {
        $query = $this->normalizer->normalizeLine(
            '{"timestamp":"2026-08-28T23:05:29.807382+0800","flow_id":371385289636133,"event_type":"dns",'
            . '"src_ip":"192.168.1.114","src_port":43489,"dest_ip":"8.8.8.8","dest_port":53,"proto":"UDP",'
            . '"dns":{"version":2,"type":"query","id":30044,"rrname":"api.github.com","rrtype":"AAAA","tx_id":1,"opcode":0}}'
        );

        $this->assertIsArray($query);
        $this->assertSame([], $this->rules->evaluate($query));
        $this->assertSame(0, $this->rules->basis()['answers'], 'a query is not an answer');

        // A socket event must fall straight through rather than being read as a
        // DNS event with everything missing.
        $this->assertSame([], $this->rules->evaluate(['action' => 'net_connect', 'network' => []]));
    }

    /**
     * A state file cannot blind the window either.
     *
     * observe() refuses a timestamp far in the future, because adopting one
     * makes prune() drop every bucket while observedSpan() still claims a full
     * window: the rules then read a complete basis holding nothing, which is
     * silence that looks like an answer. restore() took the clock straight out
     * of the state file, so the same blindness was reachable through the state
     * this module writes every cycle — and one NTP step forward is enough to
     * write it.
     */
    public function test_a_future_clock_in_restored_state_cannot_blind_the_window(): void
    {
        $window = new DnsResolutionWindow();
        $now = (float) time();

        $window->restore([
            'clock' => $now + 86400.0,
            'first_observed' => $now,
            'nxdomain' => [],
            'buckets' => [],
            'fired' => [],
        ]);

        $this->assertLessThanOrEqual($now + 600.0, $window->clock(), 'the restored clock is clamped, not adopted');
        $this->assertSame(1, $window->refusals()['future'], 'and the refusal is counted');

        // With the clock clamped the window can still take evidence, which is
        // the whole point: a blinded window accepts rows and retains none.
        $rules = new DnsAnomalyRules($window);
        $fired = [];

        foreach ($this->dgaLabels(14, 12, 5150) as $index => $label) {
            foreach ($rules->evaluate(
                $this->real(self::ANSWER_DOCKER_NXDOMAIN, $now + $index * 1.5, $label . '.restored-example.com')
            ) as $finding) {
                $fired[] = $finding['rule'];
            }
        }

        $this->assertSame(['DNS-001'], $fired, 'the window still holds what it observes');
    }

    /* ------------------------------------------------------------------ */
    /* Helpers                                                             */
    /* ------------------------------------------------------------------ */

    /**
     * A real log line with the clock, and optionally the name, replaced.
     *
     * Everything else the rules read stays exactly as Suricata wrote it.
     */
    private function real(string $line, float $ts, ?string $name = null): array
    {
        $row = json_decode($line, true);
        $row['timestamp'] = $this->stamp($ts);

        if ($name !== null) {
            $row['dns']['rrname'] = $name;
        }

        $event = $this->normalizer->normalize($row);

        $this->assertIsArray($event, 'the synthetic row must still normalise');

        return $event;
    }

    /** A real resolving answer, with the name replaced. */
    private function resolved(string $name, float $ts, string $address = '185.199.108.153'): array
    {
        $row = json_decode(self::ANSWER_GITHUB_RESOLVED, true);
        $row['timestamp'] = $this->stamp($ts);
        $row['dns']['rrname'] = $name;
        $row['dns']['answers'][0]['rrname'] = $name;
        $row['dns']['answers'][0]['rdata'] = $address;
        $row['dns']['grouped']['A'] = [$address];

        $event = $this->normalizer->normalize($row);

        $this->assertIsArray($event);

        return $event;
    }

    /**
     * An eve.json timestamp for an instant, in the offset the log really uses.
     *
     * Built through DateTimeImmutable rather than date(), because the process
     * timezone is not the log's: PHP's ini default here is UTC while the
     * application sets Asia/Taipei, so a stamp formatted with the ambient
     * timezone would name an instant eight hours from the one intended.
     */
    private function stamp(float $ts): string
    {
        $seconds = (int) floor($ts);
        $micro = (int) round(($ts - $seconds) * 1_000_000);

        return (new DateTimeImmutable('@' . $seconds))
            ->setTimezone(new DateTimeZone('+08:00'))
            ->format('Y-m-d\TH:i:s') . sprintf('.%06d+0800', $micro);
    }

    /**
     * Distinct generated labels, the shape a DGA emits.
     *
     * Seeded, so a failure is reproducible; a random burst that fails once and
     * passes on rerun teaches nothing. Measured over five seeds, 30 labels of
     * 12 base36 characters carry a mean leftmost entropy of 3.284 to 3.317 and
     * put 18 to 25 of the 30 above a digit ratio of 0.2.
     *
     * @return array<int, string>
     */
    private function dgaLabels(
        int $count,
        int $length,
        int $seed,
        string $alphabet = 'abcdefghijklmnopqrstuvwxyz0123456789'
    ): array {
        mt_srand($seed);

        $labels = [];
        $span = strlen($alphabet) - 1;

        while (count($labels) < $count) {
            $label = '';

            for ($i = 0; $i < $length; $i++) {
                $label .= $alphabet[mt_rand(0, $span)];
            }

            // Distinct by construction: a repeat would quietly weaken the
            // distinct-count assertion it is used for.
            $labels[$label] = true;
        }

        return array_keys($labels);
    }

    /**
     * Replay labels three per 30-second process, as the watchdog really runs.
     *
     * @param array<int, string> $labels
     * @return array<int, array>
     */
    private function replayInCycles(array $labels, bool $carry): array
    {
        $state = [];
        $findings = [];

        foreach (array_chunk($labels, 3) as $cycle => $chunk) {
            $window = new DnsResolutionWindow();

            if ($carry && $state !== []) {
                $window->restore($state);
            }

            $rules = new DnsAnomalyRules($window);

            foreach ($chunk as $offset => $label) {
                $findings = array_merge($findings, $rules->evaluate($this->real(
                    self::ANSWER_DOCKER_NXDOMAIN,
                    self::T0 + ($cycle * 30) + ($offset * 3),
                    $label . '.slow-dga-example.com'
                )));
            }

            $state = $window->export();
        }

        return $findings;
    }

    /**
     * Raw dns lines from the tail of the live log.
     *
     * The tail is 192MB because DNS is sparse in this file: measured, the last
     * 16MB holds 3,707 dns rows and the last 64MB holds 19,286, because
     * eve.json also carries alert, flow, http and tls records and runs at
     * roughly 80MB an hour on this host. 192MB is what it takes to reach 20,000
     * DNS rows, and it reads in 0.15 seconds warm.
     *
     * @return array<int, string>
     */
    private function liveDnsLines(int $tailBytes = 192 * 1024 * 1024, int $cap = 40000): array
    {
        if (!is_readable(self::LIVE_LOG)) {
            return [];
        }

        $size = (int) @filesize(self::LIVE_LOG);
        $handle = @fopen(self::LIVE_LOG, 'rb');

        if ($handle === false) {
            return [];
        }

        if ($size > $tailBytes) {
            fseek($handle, $size - $tailBytes);
            // Discard the partial line the seek landed inside.
            fgets($handle);
        }

        $lines = [];

        while (count($lines) < $cap && ($line = fgets($handle)) !== false) {
            if (str_contains($line, '"event_type":"dns"')) {
                $lines[] = $line;
            }
        }

        fclose($handle);

        return $lines;
    }

    /**
     * One event timestamped in the future must not blind the window for good.
     *
     * `observe()` took the maximum of the clock and the event time, justified by
     * a measured 2.841ms of reordering in the log. The justification was right
     * and the bound was missing: a single row from the future pushed the clock
     * there permanently, `prune()` then dropped every bucket as too old, and
     * `observedSpan()` still returned a full window because it measured
     * `clock - firstObserved`.
     *
     * So the rules downstream would have read "a complete window of basis, and
     * nothing seen" when the truth was "everything was discarded" — the exact
     * conflation of "we did not see" with "it did not happen" that this window
     * exists to prevent, reachable from one bad row and with nothing logged.
     */
    public function test_a_future_timestamp_cannot_blind_the_window(): void
    {
        $window = new \App\Services\Network\DnsResolutionWindow();
        $now = (float) time();

        // A normal run of traffic first.
        for ($i = 0; $i < 12; $i++) {
            $window->observe("host{$i}.example.com", 'example.com', true, $now - 60 + $i);
        }

        $spanBefore = $window->observedSpan();
        $this->assertGreaterThan(0.0, $spanBefore, 'twelve real events are a basis');

        // Then one row a year in the future.
        $window->observe('corrupt.example.com', 'example.com', true, $now + 31_536_000);

        $this->assertSame(1, $window->refusals()['future'], 'the refusal must be counted, not silent');
        $this->assertEqualsWithDelta(
            $spanBefore,
            $window->observedSpan(),
            1.0,
            'the basis must survive the bad row rather than being reported as full and empty'
        );

        // And the real traffic is still there to judge against.
        $window->observe('host99.example.com', 'example.com', true, $now);
        $this->assertGreaterThan(0.0, $window->observedSpan());
    }

    /**
     * An empty window reports no basis, whatever the clock says. Deriving the
     * span from the first event ever seen keeps claiming a full window after a
     * prune has emptied it.
     */
    public function test_an_emptied_window_reports_no_basis(): void
    {
        $window = new \App\Services\Network\DnsResolutionWindow();
        $now = (float) time();

        $window->observe('a.example.com', 'example.com', true, $now - 4000);
        $this->assertGreaterThanOrEqual(0.0, $window->observedSpan());

        // Move well past the window so the early bucket is pruned out.
        $window->observe('b.example.com', 'example.com', true, $now);

        $span = $window->observedSpan();
        $this->assertLessThanOrEqual(
            300.0,
            $span,
            'the span may never exceed the window it claims to cover'
        );
    }

    /**
     * Ordinary reverse DNS must not read as a DGA burst.
     *
     * Resolving an address queries a name of digit labels ending in
     * in-addr.arpa, and an address with no PTR record answers NXDOMAIN. So a
     * host resolving addresses in bulk produces exactly what these rules key
     * on: many distinct, digit-heavy, non-existent names in one window. Before
     * the exemption DNS-001 graded that critical.
     *
     * The sibling tunnelling rules exempted this shape from the start; these
     * had no reverse handling at all. The corpus on this host holds 10 such
     * lookups (138.77.249.66.in-addr.arpa and similar) and anything resolving
     * addresses in bulk — a log analyser, a mail server — makes hundreds.
     */
    public function test_reverse_dns_is_not_mistaken_for_a_domain_generation_burst(): void
    {
        $now = (float) time();
        $findings = [];

        // Forty distinct reverse lookups, all NXDOMAIN, inside one window:
        // a log analyser resolving a page of client addresses.
        for ($i = 0; $i < 40; $i++) {
            $name = sprintf('%d.%d.249.66.in-addr.arpa', $i, 100 + $i);

            foreach ($this->rules->evaluate($this->real(self::ANSWER_DOCKER_NXDOMAIN, $now + $i * 0.5, $name)) as $finding) {
                $findings[] = $finding['rule'] . ' ' . $finding['reason'];
            }
        }

        $this->assertSame([], $findings, 'reverse DNS is not evidence of a generated domain');
        $this->assertSame(
            40,
            $this->rules->exclusions()['reverse'],
            'and the exclusion is counted rather than silent, so a coverage report can say why'
        );

        // The predicate is shared with the tunnelling rules, so the two cannot
        // drift apart again.
        $this->assertTrue(DnsEventNormalizer::isReverseLookupName('138.77.249.66.in-addr.arpa'));
        $this->assertTrue(DnsEventNormalizer::isReverseLookupName(
            '1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa'
        ));
        $this->assertFalse(DnsEventNormalizer::isReverseLookupName('api.github.com'));
        $this->assertFalse(
            DnsEventNormalizer::isReverseLookupName('1.2.3.example.com'),
            'three numeric labels is not an address written backwards'
        );
    }

    /**
     * The exemption is narrow: it must not become a way to hide.
     *
     * Digit labels are cheap to write, so a channel that prefixed four of them
     * would be exempt if the suffix were not required. It is.
     */
    public function test_the_reverse_exemption_does_not_cover_a_digit_prefixed_generated_name(): void
    {
        $now = (float) time();
        $findings = [];

        foreach ($this->dgaLabels(30, 12, 20260902) as $i => $label) {
            foreach ($this->rules->evaluate($this->real(
                self::ANSWER_DOCKER_NXDOMAIN,
                $now + $i * 0.5,
                '1.2.3.4.' . $label . '.example.net'
            )) as $finding) {
                $findings[] = $finding['rule'];
            }
        }

        $this->assertNotSame([], $findings, 'four leading digit labels must not buy an exemption');
        $this->assertSame(
            ['reverse' => 0, 'reduced' => 30],
            $this->rules->exclusions(),
            'nothing was dropped: the address was removed and what was behind it was judged'
        );
    }

}
